### ISSUE TITLE
Forever Enough Items Crashes When Trying to Click on Items 

### ISSUE THREAD

**Issue by Diablo1290** [elix-x/Forever-Enough-Items#24] opened 2016-06-27 03:46 UTC
Okay, so, I recently installed this mod and after a couple of hours of trying to figure out "How" to permission myself on singleplayer... I figured it out. But now... Every time I click on any of the blocks, swords, tools, etc..., the game completely crashes "Shutting Down Internal Server"... I've uninstalled every mod and kept Forever Enough Items Mod and its corresponding mods and it still crashes.

Please help.

**Comment by Elix-x** [comment] 2016-06-27 06:56
Please post crash report. Either on pastebin or gist.

**Comment by DerIlias** [comment] 2016-06-27 15:15
Same problem
[crash report](http://pastebin.com/auyWQW4Q)

**Comment by Elix-x** [comment] 2016-06-27 15:21
Duplicate of #23.

**Closed as completed** 2016-06-28 09:05 UTC
Labels: duplicate, crash, JEI override
