### ISSUE TITLE
MC Crashing with FEI

### ISSUE THREAD

**Issue by Viking8** [elix-x/Forever-Enough-Items#55] opened 2016-11-10 00:01 UTC
Greetings,

I have MC 1.10.2 with both forge-1.10.2-12.18.2.2099 and forge-1.10.2-12.18.2.22133 installed. It doesn't seem to matter what other mods are in my mods folder, FEI crashes minecraft everytime. I take it out and minecraft loads just fine. I tried it out on 3 other PC's that my nephews use to play with me when they come over, but it's the same story for all of them. Not sure what to do next. Any ideas? I've included my last crash report. Thanks for any help you can provide! 

[mc-forge-crash-report.txt](https://github.com/Elix-x/Forever-Enough-Items/files/582225/mc-forge-crash-report.txt)

**Comment by Elix-x** [comment] 2016-11-10 16:36
Duplicate of #49.

TLDR: Please install latest Excore and JEI builds. This will fix it.

So this still was not fixed... Huh... Hopefully it will be finally fixed in 1.1.

**Comment by Viking8** [comment] 2016-11-11 00:16
That did the trick! I didn't realize I was on older versions of those two mods. It can be hard to find the newest versions sometimes with so many sites having versions to download. Sorry about the duplicate by the way!

**Comment by Elix-x** [comment] 2016-11-11 08:34
No problems!

Also, there is only one official place for download - curse/curseforge (they are kinda the same). All others are "illegaly" reposting mods (more about it here - http://stopmodreposts.org/).

**Closed as completed by Elix-x** 2016-11-11 08:34 UTC
Labels: bug, duplicate
