### ISSUE TITLE
1.10.2 Crash

### ISSUE THREAD

**Issue by ansiliden** [elix-x/Forever-Enough-Items#35] opened 2016-08-02 11:23 UTC
Help please. i did have the other recommended mods but uninstalled as i thought they were the problem. 
[crash-2016-08-02_21.15.04-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/396858/crash-2016-08-02_21.15.04-client.txt)

**Comment by Elix-x** [comment] 2016-08-02 11:42
Duplicate of #33.

**Closed as completed by Elix-x** 2016-08-02 11:42 UTC
Labels: duplicate, crash
