### ISSUE TITLE
Crash with item subsets

### ISSUE THREAD

**Issue by Seaer1** [elix-x/Forever-Enough-Items#45] opened 2016-10-02 13:43 UTC
[crash-2016-10-02_16.02.29-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/504989/crash-2016-10-02_16.02.29-client.txt)
Every time i try to use shift left click under item subsets on any mod it just crashes the game instead of displaying the selected mods content.

Other info:
Minecraft:1.10.2
forge:1.10.2-12.8.1.2094
JEI:1.10.2-3.12.3.292
FEI:1.0.15-1.10.2

**Comment by Elix-x** [comment] 2016-10-02 14:01
Please post crash report.

**Comment by Seaer1** [comment] 2016-10-02 14:15
@elix-x added crash report to the first comment.

**Comment by Elix-x** [comment] 2016-10-02 14:22
Duplicate of #42.

**Comment by Elix-x** [comment] 2016-10-02 14:23
Will be / is fixed in 1.1 and 1.0.16 which will be released today.

**Closed as completed** 2016-10-02 16:30 UTC
Labels: duplicate, crash, JEI override
