### ISSUE TITLE
crash on change icon

### ISSUE THREAD

**Issue by jdratlif** [elix-x/Forever-Enough-Items#48] opened 2016-10-21 18:32 UTC
FEI crashes minecraft when you try to change the profile icon.

Steps to reproduce:

Start Minecraft
Open Inventory Screen
Open Profile Edit Screen
Select Profile
Left click on icon
CRASH

Happens every time I've tried it.

MultiMC log, Crash Log, and latest.log from Minecraft are in this archive
http://games.technoplaza.net/temp/fei-iconcrash.zip

Minecraft Info:

Minecraft 1.10.2
Forge 2099
JEI 3.12.7.312
Excore 1.6.2
FEI 1.0.16

Thanks for a great mod. If I can provide any more information, please let me know. More than happy to help test.

**Comment by Elix-x** [comment] 2016-10-21 19:49
Probably caused by newer JEI version.
Try downgrading to JEI 293, and see if this helps.

Will be fixed in next version in any case.

**Comment by jdratlif** [comment] 2016-10-21 20:40
I see they released a new stable last week, version 323, but it still crashes with that version. It works on 297, the last stable release before 312.

Thanks.

**Comment by Elix-x** [comment] 2016-10-21 21:03
Thank you. That's all information i needed.

This will be fixed in the next version.

**Closed as completed** 2016-10-26 17:12 UTC
Labels: crash, JEI override
