### ISSUE TITLE
Minecraft crashes (Help)

### ISSUE THREAD

**Issue by yagizcamo93** [elix-x/Forever-Enough-Items#37] opened 2016-08-31 23:28 UTC
I installed all of the necessary mods but it crashes in the loading screen.

[crash-2016-09-01_02.04.16-client.txt](https://github.com/elix-x/Forever-Enough-Items/files/448458/crash-2016-09-01_02.04.16-client.txt)
[latest.txt](https://github.com/elix-x/Forever-Enough-Items/files/448459/latest.txt)

**Comment by Elix-x** [comment] 2016-09-01 07:13
Duplicate of #33.

**Closed as completed by Elix-x** 2016-09-01 07:13 UTC
Labels: duplicate, crash

**Comment by Elix-x** [comment] 2016-09-01 07:15
TLDR: Update excore to 1.6.2/1.6.1.
